---
title: "Chapter 2 - Approach and Methodology"
author: "Adrien Ratsimbaharison"
date: "10/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The problem: Challenges in analyzing political stability

1) We need to analyze political stability, instability and crisis in terms of conflict, i.e. as different stages in the "curve of conflict" within a given society.

2) As a stage of conflict, and in application of what we have learned for the analysis of conflict (See my book, The Political Crisis of March 2009), the escalations and deescalations from political stability to instability and crisis depend on two factors:

- conditions (or contexts of the conflict), 
- triggers (which include behaviors, tactics and strategies of the actors in the conflict)

## The need to use a "mixed methods research" as defined by John Creswell


## The design of the "mixed methods research"


## A quantitative research method to identify the major factors influencing political stability, instability and crisis


## A qualitative research method to identify the major triggers leading to the escalation (or deescalation) from political stability, instability and crisis



#### Case study methods to illustrate how conditions and triggers contribute to the escalation (or deescalation) from political stability, instability and crisis in some countries

