---
title: "Collecting and Cleaning the Quantitative Data Used in this Project"
author: "Adrien Ratsimbaharison"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading and Cleaning the Data on World Governance Indicators (WGI) from the World Bank Website Using `webstats`


```{r warning=FALSE}
library(wbstats)
library(readr)
library(lubridate)
library(dplyr)
library(Hmisc)
library(caret)
library(kernlab)
library(stringr)
library(knitr)

# As we collected the data from the World Bank, we realized that the country names and codes were not consistent throughout the database and between the World Bank and other organizations, such as the United Nations.
# Thus, in order to be consistent throughout the data collection and analysis, we need decided to adopt the World Bank country names and codes as explained in the following webpage: [API: Country Queries](https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-api-country-queries)
# The file `WBCountryIso2c_Iso3c_M49Code.csv` was made by hand based on the information provided by the World Bank.

# downloading the data on World Governance Indicators
#data on stability estimate
stabilityDf <- wb(country = "countries_only", indicator = "PV.EST", 
                          startdate = 1996, enddate = 2018, POSIXct = TRUE)
stabilityDf <- tbl_df(stabilityDf)
stabilityDf <- select(stabilityDf, country, iso2c, date, stability = value)
head(stabilityDf)


# creating a variable for stability category with dplyr
stabilityDf <- stabilityDf %>% mutate(stabilityCategory=cut(stability, breaks=c(-Inf, -1, 0, 1, Inf), labels=c("Highly Unstable","Moderately Unstable","Moderately Stable", "Highly Stable")))
head(stabilityDf)
str(stabilityDf)

#data on control of corruption estimate
corruptionControlDf <- wb(country = "countries_only", indicator = "GV.CONT.CO.ES", 
                          startdate = 1996, enddate = 2018, POSIXct = TRUE)
corruptionControlDf <- tbl_df(corruptionControlDf)
corruptionControlDf <- select(corruptionControlDf, country, iso2c, date, corruptionControl = value)
head(corruptionControlDf)

# In order to be consistent throughout the data collection and analysis, we need to replace "Cape Verde" with"Cabo Verde"
corruptionControlDf$country <- str_replace(corruptionControlDf$country, "Cape Verde", "Cabo Verde")


#data on government effectiveness estimate
governmentEffectivenessDf <- wb(country = "countries_only", indicator = "GV.GOVT.EF.ES", 
                          startdate = 1996, enddate = 2018, POSIXct = TRUE)
governmentEffectivenessDf <- tbl_df(governmentEffectivenessDf)
governmentEffectivenessDf <- select(governmentEffectivenessDf, country, iso2c, date, governmentEffectiveness = value)
head(governmentEffectivenessDf)

# In order to be consistent throughout the data collection and analysis, we need to replace "Cape Verde" with"Cabo Verde"
governmentEffectivenessDf$country <- str_replace(governmentEffectivenessDf$country, "Cape Verde", "Cabo Verde")


#data on regulatory quality estimate
regulatoryQualityDf <- wb(country = "countries_only", indicator = "RQ.EST", 
                          startdate = 1996, enddate = 2018, POSIXct = TRUE)
regulatoryQualityDf <- tbl_df(regulatoryQualityDf)
regulatoryQualityDf <- select(regulatoryQualityDf, country, iso2c, date, regulatoryQuality = value)
head(regulatoryQualityDf)

# In order to be consistent throughout the data collection and analysis, we need to replace "Cape Verde" with"Cabo Verde"
regulatoryQualityDf$country <- str_replace(regulatoryQualityDf$country, "Cape Verde", "Cabo Verde")


#data on rule of law estimate
ruleOfLawDf <- wb(country = "countries_only", indicator = "GV.RULE.LW.ES", 
                          startdate = 1996, enddate = 2018, POSIXct = TRUE)
ruleOfLawDf <- tbl_df(ruleOfLawDf)
ruleOfLawDf <- select(ruleOfLawDf, country, iso2c, date, ruleOfLaw = value)
head(ruleOfLawDf)

# In order to be consistent throughout the data collection and analysis, we need to replace "Cape Verde" with"Cabo Verde"
ruleOfLawDf$country <- str_replace(ruleOfLawDf$country, "Cape Verde", "Cabo Verde")

#data on voice and accountability estimate
voiceAndAccountabilityDf <- wb(country = "countries_only", indicator = "GV.VOIC.AC.ES", 
                          startdate = 1996, enddate = 2018, POSIXct = TRUE)
voiceAndAccountabilityDf <- tbl_df(voiceAndAccountabilityDf)
voiceAndAccountabilityDf <- select(voiceAndAccountabilityDf, country, iso2c, date, voiceAndAccountability = value)
head(voiceAndAccountabilityDf)

# In order to be consistent throughout the data collection and analysis, we need to replace "Cape Verde" with"Cabo Verde"
voiceAndAccountabilityDf$country <- str_replace(voiceAndAccountabilityDf$country, "Cape Verde", "Cabo Verde")

# joining the data on WGI
WGI <- full_join(stabilityDf, corruptionControlDf, by = c("country", "iso2c", "date")) %>%
  full_join(., governmentEffectivenessDf, by = c("country", "iso2c", "date")) %>%
  full_join(., regulatoryQualityDf, by = c("country", "iso2c", "date")) %>%
  full_join(., ruleOfLawDf, by = c("country", "iso2c", "date")) %>%
  full_join(., voiceAndAccountabilityDf, by = c("country", "iso2c", "date"))
WGI <- tbl_df(WGI)
head(WGI)
tail(WGI)



# downloading the data on country code with region and subregion from a github repository maintained by Luke Duncalfe   
# at: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv
# According to the author and contributors, "These lists are the result of merging data from two sources, the Wikipedia ISO 3166-1 article for alpha and numeric country codes, and the UN Statistics site for countries' regional, and sub-regional codes. In addition to countries, it includes dependent territories."

regionSubregionDf <- read_csv("https://raw.githubusercontent.com/aratsimbaharison/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv")
regionSubregionDf <- tbl_df(regionSubregionDf)
regionSubregionDf <- select(regionSubregionDf, country = name, iso2c = `alpha-2`, iso3c = `alpha-3`, 
                            M49Code = `country-code`, region, subregion = `sub-region`)
regionSubregionDf <- na.omit(regionSubregionDf) # this will get rid of some locations that does not have codes

# In order to be consistent throughout the data collection and analysis we need to change the names of the following countries to align them with the list of countries in the World Bank dataframes.

# The following country names have been changed:

regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Bahamas", "Bahamas, The")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Bolivia (Plurinational State of)", "Bolivia")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Congo", "Congo, Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Congo (Democratic Republic of the)", "Congo, Dem. Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Côte d'Ivoire", "Cote d'Ivoire")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Egypt", "Egypt, Arab Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Gambia", "Gambia, The")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Hong Kong", "Hong Kong SAR, China")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Korea (Democratic People's Republic of)", "Korea, Dem. People's Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Korea (Republic of)", "Korea, Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Iran (Islamic Republic of)", "Iran, Islamic Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Lao People's Democratic Republic", "Lao PDR")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Macedonia (the former Yugoslav Republic of)", "Macedonia, FYR")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Kyrgyzstan", "Kyrgyz Republic")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Macao", "Macao SAR, China")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Micronesia (Federated States of)", "Micronesia, Fed. Sts")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Moldova (Republic of)", "Moldova")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Palestine, State of", "West Bank and Gaza")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Slovakia", "Slovakia Republic")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Taiwan, Province of China", "Taiwan, China")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Tanzania, United Republic of", "Tanzania")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "United States of America", "United States")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Yemen", "Yemen, Rep.")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Viet Nam", "Vietnam")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Venezuela (Bolivarian Republic of)", "Venezuela")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Saint Kitts and Nevis", "St. Kitts and Nevis")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Saint Vincent and the Grenadines", "St. Vincent and the Grenadines")
regionSubregionDf$country <- replace(regionSubregionDf$country, regionSubregionDf$country == "Saint Lucia", "St. Lucia")
regionSubregionDf$iso3c <- replace(regionSubregionDf$iso3c, regionSubregionDf$iso3c == "COD", "ZAR")

# The following country names have been deleted:

regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Bonaire, Sint Eustatius and Saba",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Åland Islands",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Anguilla",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Falkland Islands (Malvinas)",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "French Guiana",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "French Polynesia",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Gibraltar",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Guadeloupe",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Holy See",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Isle of Man",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Guernsey",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Jersey",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Martinique",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Mayotte",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Montserrat",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Northern Mariana Islands",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Réunion",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Saint Barthélemy",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Saint Helena, Ascension and Tristan da Cunha",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Saint Martin (French part)",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Sint Maarten (Dutch part)",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Tokelau",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Turks and Caicos Islands",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Wallis and Futuna",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Svalbard and Jan Mayen",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "New Caledonia",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Norfolk Island",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Pitcairn",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Saint Barthélemy",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Saint Pierre and Miquelon",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Western Sahara",]
regionSubregionDf <- regionSubregionDf[! regionSubregionDf$country == "Virgin Islands (British)",]

View(regionSubregionDf)             

#joining the data on WGI with the UN classification by region and subregion
WGIbyCountryAndRegion <- left_join(WGI, regionSubregionDf, by = c("country", "iso2c"))
WGIbyCountryAndRegion <- tbl_df(WGIbyCountryAndRegion)
head(WGIbyCountryAndRegion)
names(WGIbyCountryAndRegion)
WGIbyCountryAndRegion <- select(WGIbyCountryAndRegion, country, M49Code = countryCode, iso2c, iso3c, date, stability, stabilityCategory, corruptionControl, governmentEffectiveness, regulatoryQuality, ruleOfLaw, voiceAndAccountability, region, subregion)
names(WGIbyCountryAndRegion)

# # making the data on WGI available in the local repository
# WGIbyCountryAndRegion <- write.csv(WGIbyCountryAndRegion, "WGIbyCountryAndRegion.csv")
# WGIbyCountryAndRegion <- tbl_df(WGIbyCountryAndRegion)


```

## Downloading and Cleaning the Data on Development, Inequality, and Poverty from the World Bank Website Using `webstats`


```{r warning=FALSE}
library(wbstats)
library(readr)
library(lubridate)
library(dplyr)
library(Hmisc)
library(caret)
library(kernlab)
library(stringr)
library(knitr)

#data on GNI per capita (constant 2010 US$) (NY.GNP.PCAP.KD)
GNIperCapitaDf <- wb(country = "countries_only", indicator = "NY.GNP.PCAP.KD", 
                     startdate = 1996, enddate = 2018, POSIXct = TRUE)
GNIperCapitaDf <- tbl_df(GNIperCapitaDf)
GNIperCapitaDf <- select(GNIperCapitaDf, country, iso2c, date, value)
GNIperCapitaDf <- rename(GNIperCapitaDf, GNIperCapita = value)
head(GNIperCapitaDf)

#data on human development index (UNDP.HDI.XD)
HDIDf <- wb(country = "countries_only", indicator = "UNDP.HDI.XD", 
            startdate = 1996, enddate = 2018, POSIXct = TRUE)
HDIDf <- tbl_df(HDIDf)
HDIDf <- select(HDIDf, country, iso2c, date, value)
HDIDf <- rename(HDIDf, HDI = value)
head(HDIDf)

#data on social inequality measured in terms of the World Bank's GINI index (SI.POV.GINI)
GINIDf <- wb(country = "countries_only", indicator = "SI.POV.GINI", 
            startdate = 1996, enddate = 2018, POSIXct = TRUE)
GINIDf <- tbl_df(GINIDf)
GINIDf <- select(GINIDf, country, iso2c, date, value)
GINIDf <- rename(GINIDf, GINI = value)
head(GINIDf)


# data on poverty measured in terms of the World Bank's Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population) (SI.POV.DDAY)

povHeadCountDF <- wb(country = "countries_only", indicator = "SI.POV.DDAY", 
            startdate = 1996, enddate = 2018, POSIXct = TRUE)
povHeadCountDF <- tbl_df(povHeadCountDF)
povHeadCountDF <- select(povHeadCountDF, country, iso2c, date, value)
povHeadCountDF <- rename(povHeadCountDF, povertyHeadCount = value)
head(povHeadCountDF)

# joining the data on development, social inequality, and poverty: devIneqPovDF
devIneqPovDF <- full_join(GNIperCapitaDf, HDIDf, by = c("country", "iso2c", "date")) %>%
  full_join(., GINIDf, by = c("country", "iso2c", "date")) %>%
  full_join(., povHeadCountDF, by = c("country", "iso2c", "date"))
  
devIneqPovDF <- tbl_df(devIneqPovDF)
head(devIneqPovDF)
devIneqPovDF$date <- as.integer(devIneqPovDF$date)
names(devIneqPovDF)

# # making the data on development, social inequality and poverty available in the local repository
# devIneqPovDF <- write.csv(devIneqPovDF, "devIneqPovDF.csv")
# devIneqPovDF <- tbl_df(devIneqPovDF)


# joining the data on WGI by country and region, development, social inequality, and poverty
# (WGIdevIneqPovDF)
WGIbyCountryAndRegion <- read.csv("WGIbyCountryAndRegion.csv")
WGIdevIneqPovDF <- full_join(WGIbyCountryAndRegion, devIneqPovDF, by = c("country", "iso2c", "date"))
WGIdevIneqPovDF <- tbl_df(WGIdevIneqPovDF)
WGIdevIneqPovDF$date <- as.integer(WGIdevIneqPovDF$date)
head(WGIdevIneqPovDF)
names(WGIdevIneqPovDF)

# # making the data on WGI, development, social inequality and poverty (WGIdevIneqPovDF) available in the local repository
# WGIdevIneqPovDF <- write.csv(WGIdevIneqPovDF, "WGIdevIneqPovDF.csv")
# WGIdevIneqPovDF <- tbl_df(WGIdevIneqPovDF)
# 

```

## Downloading and Cleaning the Data on regime types from Freedom House, Polity IV and 

```{r warning= FALSE}

library(wbstats)
library(readr)
library(lubridate)
library(dplyr)
library(Hmisc)
library(caret)
library(kernlab)
library(stringr)
library(knitr)

#data on political system, revised combined polity score (UPP.REV.POL.XQ) - see Polity IV
polityScoreDf <- wb(country = "countries_only", indicator = "UPP.REV.POL.XQ", 
                    startdate = 1996, enddate = 2018, POSIXct = TRUE)
polityScoreDf <- select(polityScoreDf, country, iso2c, date, value)
polityScoreDf <- rename(polityScoreDf, polityScore = value)
head(polityScoreDf)

# creating a new variable for polity category (polityCategory)
polityScoreDf <- polityScoreDf %>% mutate(polityCategory=cut(polityScore, breaks=c(-Inf, -6, 6, Inf), labels=c("Autocracy","Anocracy","Democracy")))
head(polityScoreDf)

#data on political system, Institutionalized democracy (UPP.INS.DEMO.XQ) - see Polity IV
democracyDf <- wb(country = "countries_only", indicator = "UPP.INS.DEMO.XQ", 
                  startdate = 1996, enddate = 2018, POSIXct = TRUE)
democracyDf <- select(democracyDf, country, iso2c, date, value)
democracyDf <- rename(democracyDf, democracyInst = value)
head(democracyDf)

#data on political system, Institutionalized autocracy (UPP.INS.AUTO.XQ) - see Polity IV
autocracyDf <- wb(country = "countries_only", indicator = "UPP.INS.AUTO.XQ", 
                  startdate = 1996, enddate = 2018, POSIXct = TRUE)
autocracyDf <- select(autocracyDf, country, iso2c, date, value)
autocracyDf <- rename(autocracyDf, autocracyInst = value)
head(autocracyDf)

# downloadong the "Stata Friendly Freedom House Data, 1973-2018" on political right and civil liberty maintained by Amanda B. Edgell, University of Florida (homepage: https://acrowinghen.com/data/)
 
library(readxl)
url <- "https://acrowinghen.files.wordpress.com/2018/05/fh_rankings_1973_2018.xlsx"
destfile <- "fh_rankings_1973_2018.xlsx"
curl::curl_download(url, destfile)
fh_rankings_1973_2018 <- read_excel(destfile, sheet = 3)
freedomHouseDF <- read_excel("fh_rankings_1973_2018.xlsx", sheet = 3)
freedomHouseDF <- tbl_df(freedomHouseDF)
head(freedomHouseDF)
names(freedomHouseDF)

freedomHouseDF <- select(freedomHouseDF, country, year, pr, cl, mean, status, inverse_pr, inverse_cl, inverse_mean, sum)
freedomHouseDF <- filter(freedomHouseDF, year>= 1996)
freedomHouseDF <- rename(freedomHouseDF, date = year)
freedomHouseDF$date <- as.character(freedomHouseDF$date)
head(freedomHouseDF)


# In order to be consistent throughout the data collection and analysis we need to change the names of the following countries to align them with the list of countries in the World Bank dataframes.

# The following country names have been changed:

freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Bahamas", "Bahamas, The")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Brunei", "Brunei Darussalam")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Cape Verde", "Cabo Verde")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Congo (Brazzaville)", "Congo, Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Congo (Kinshasa)", "Congo, Dem. Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Egypt", "Egypt, Arab Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Iran", "Iran, Islamic Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Kyrgyzstan", "Kyrgyz Republic")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Lao", "Lao PDR")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Macedonia", "Macedonia, FYR")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Micronesia", "Micronesia, Fed. Sts")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "North Korea", "Korea, Dem. People's Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Russia", "Russian Federation")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Slovakia", "Slovak Republic")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "South Korea", "Korea, Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Syria", "Syrian Arab Republic")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Yemen", "Yemen, Rep.")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Taiwan", "Taiwan, China")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Trinidad & Tobago", "Trinidad and Tobago")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Saint Vincent & Grenadines", "St. Vincent and Grenadines")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Antigua & Barbuda", "Antigua and Barbuda")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Saint Kitts and Nevis", "St. Kitts and Nevis")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Sao Tome & Principe", "Sao Tome and Principe")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Saint Lucia", "St. Lucia")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "Bosnia-Herzegovina", "Bosnia and Herzegovina")
freedomHouseDF$country <- replace(freedomHouseDF$country, freedomHouseDF$country == "East Timor", "Timor-Leste")



# The following country names have been deleted:

freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Germany, W.",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Germany, E.",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Czechoslovakia",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Yugoslavia (Serbia & Montenegro)",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "USSR",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Yemen, N.",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Yemen, S.",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Vietnam, N.",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Vietnam, S.",]
freedomHouseDF <- freedomHouseDF[! freedomHouseDF$country == "Northern Cyprus",]


# The country status have been spelled out as follows: "F" = "Free", "PF" = "Partly Free", "NF" = "Not Free"

freedomHouseDF$status <- replace(freedomHouseDF$status, freedomHouseDF$status == "F", "Free")
freedomHouseDF$status <- replace(freedomHouseDF$status, freedomHouseDF$status == "PF", "Partly Free")
freedomHouseDF$status <- replace(freedomHouseDF$status, freedomHouseDF$status == "NF", "Not Free")

head(freedomHouseDF)
freedomHouseDF <- tbl_df(freedomHouseDF)


# joining the Freedom House data with the data on region and subregion with iso2c

freedomHouseByRegionDF <- left_join(freedomHouseDF, regionSubregionDf, by = "country")
freedomHouseByRegionDF <- tbl_df(freedomHouseByRegionDF)
names(freedomHouseByRegionDF)
freedomHouseByRegionDF <- select(freedomHouseByRegionDF, country, iso2c, iso3c, M49Code, date, pr, cl, sum, mean, status, inverse_pr, inverse_cl, inverse_mean, region, subregion)
head(freedomHouseByRegionDF)
str(freedomHouseByRegionDF)


#joining the data on political stability and regime types indicators (regimeTypeDf)
WGIregimeTypeByRegionDF <- left_join(WGIbyCountryAndRegion, polityScoreDf, by = c("country", "date")) %>%
  left_join(., democracyDf, by = c("country", "date")) %>%
  left_join(., autocracyDf, by = c("country", "date")) %>%
  left_join(., freedomHouseDF, by = c("country", "date"))

WGIregimeTypeByRegionDF <- tbl_df(WGIregimeTypeByRegionDF)
WGIregimeTypeByRegionDF <- select(WGIregimeTypeByRegionDF, country, iso3c, M49Code, date, stability, stabilityCategory, corruptionControl, governmentEffectiveness, regulatoryQuality, ruleOfLaw, voiceAndAccountability, polityScore, polityCategory, democracyInst, autocracyInst, pr, cl, sum, mean, status, inverse_pr, inverse_cl, inverse_mean, region, subregion)

head(WGIregimeTypeByRegionDF)
names(WGIregimeTypeByRegionDF)
str(WGIregimeTypeByRegionDF)

```



