---
title: "Zimbabwe"
author: ""
date: ""
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Political Stability Estimate Data

The data set shows the political stability estimate of the country each year.


```{r politicalStabilityEstimateByCountry, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

library(readr)
stabilityData <- read_csv("WGI2popDevIneqPovRegimeConflict1V2.csv")
stabilityVariables <- c("country", "iso3c", "date","stability","stabilityCategory4")
stabilityData <- stabilityData[stabilityVariables]


# data by country
# country = x
x <- stabilityData[stabilityData$country == "Zimbabwe",]
x

```

## Political Stability Estimate Plot

The plot shows the trends of stabilization and destabilization for the each country. 

```{r Political Stability Plot, echo=FALSE, fig.cap="Political Stability Trend", message=FALSE, warning=FALSE, paged.print=FALSE}
library(ggplot2)
stabilityTrend <- ggplot(data=x, aes(x=date, y=stability)) +
  geom_line()+
  geom_point() +
  geom_hline(yintercept=0.0, color = "red", size = 1.25) +
   geom_hline(yintercept=1.0, linetype="dashed", color = "red", size = 1) +
   geom_hline(yintercept=-1.0, linetype="dashed", color = "red", size = 1) +
  ylim(-3.5, 2.5) + 
  xlab("Year") +
  ylab("Political Stability Estimate")

plot(stabilityTrend)

# To save the figure:
# png("stabilityTrend.png")
# 
# plot(stabilityTrend)
# 
# dev.off()

```

