---
title: "Table of Contents"
author: "Adrien Ratsimbaharison"
date: "9/15/2018"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part I - Introduction

### Chapter 1 - Political Stability: What is it and Why it Matters?

#### What is "Political Stability"?

- Some Early Attempts to Assess the Stability of Political Systems

what is supposed to be stable? the **political system** or **regime** or the **government** or **leadership**?



- Some Competing Concepts: "political order/disorder", "rogue state" and "failed state", "fragile state"



- "Political Stability" as "Likelihood of Regime Survival"



#### Why Does "Political Stability" Matter?



#### The Purpose and Argument of the Book



#### The Plan of the Book




### Chapter 2 - Political Stability: Approach and Methodology

#### The problem: Challenges in analyzing political stability

1) We need to analyze political stability, instability and crisis in terms of conflict, i.e. as different stages in the "curve of conflict" within a given society.

2) As a stage of conflict, and in application of what we have learned for the analysis of conflict (See my book, The Political Crisis of March 2009), the escalations and deescalations from political stability to instability and crisis depend on two factors:

- conditions (or contexts of the conflict), 
- triggers (which include behaviors, tactics and strategies of the actors in the conflict)

#### The need to use a "mixed methods research" as defined by John Creswell


#### The design of the "mixed methods research"


#### A quantitative research method to identify the major factors influencing political stability, instability and crisis


#### A qualitative research method to identify the major triggers leading to the escalation (or deescalation) from political stability, instability and crisis



#### Case study methods to illustrate how conditions and triggers contribute to the escalation (or deescalation) from political stability, instability and crisis in some countries



### Chapter 3 - Political Stability and Instability Around the World Since the End of the Cold War: Descriptive Statistics



## Part II - The Conditions of Political Stability, Instability and Crisis in Post-Cold War Africa

### Chapter 3 - Governance and Political Instability and Crisis

### Chapter 4 - Political Conditions of Political Instability and Crisis

### Chapter 5 - Economic and Social Conditions of Political Instability and Crisis

### Chapter 6 - Cultural, Religious, and Geographic Conditions Political Instability and Crisis



## Part III - The Triggers of Political Instability and Crisis in Post-Cold War Africa

### Chapter 7 - Electoral Processes and Political Instability and Crisis

### Chapter 8 - Politics of Exclusion and Political Instability and Crisis

### Chapter 9 - Autocratization and Political Instability and Crisis


## Part IV - Case Studies and Conclusion

### Chapter 10 - Madagascar

### Chapter 11 - Mali








