---
title: "Collecting the Qualitative Data on the Cameroon Case Study"
author: "Adrien Ratsimbaharison"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- For the most part, I use the `rvest package` for collecting the qualitative data used in this project. These qualitative data are the saved in a folder `qualitativeData` and then analyzed with the `RQDA package`. -->


## Basic information on Cameroon

```{r}
library(rvest)
library(xml2)

# From Wikipedia

Url <- "Source: https://en.wikipedia.org/wiki/Cameroon"

web_page <- read_html("https://en.wikipedia.org/wiki/Cameroon")
# extracting the header
header <- web_page %>%
        html_nodes("h1") %>%
        html_text()

# extracting the text
text <- web_page %>%
        html_nodes("p") %>%
        html_text()

# saving the text to a local repository

cameroonBasicInfo1 <- writeLines(c(header, Url, text), "cameroonBasicInfo1.txt")


# From BBC's country profile


Url <- "Source: https://www.bbc.com/news/world-africa-13146029"

web_page <- read_html("https://www.bbc.com/news/world-africa-13146029")
# extracting the header
header <- web_page %>%
        html_nodes("h1") %>%
        html_text()

# extracting the text
text <- web_page %>%
        html_nodes("p") %>%
        html_text()

# saving the text to a local repository

cameroonBasicInfo2 <- writeLines(c(header, Url, text), "cameroonBasicInfo2.txt")
```


 